/**
 * Moonlogs
 * Moonlogs API
 *
 * OpenAPI spec version: 0.5.10
 * Contact: shalpack@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RecordLevel } from '../models/RecordLevel';
import { HttpFile } from '../http/http';

export class Record {
    'id': number;
    'text': string;
    'schemaName': string;
    'schemaId'?: number;
    'query': any;
    'kind': string;
    'createdAt'?: string;
    'groupHash'?: string;
    'level'?: RecordLevel;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "id",
            "baseName": "id",
            "type": "number",
            "format": ""
        },
        {
            "name": "text",
            "baseName": "text",
            "type": "string",
            "format": ""
        },
        {
            "name": "schemaName",
            "baseName": "schema_name",
            "type": "string",
            "format": ""
        },
        {
            "name": "schemaId",
            "baseName": "schema_id",
            "type": "number",
            "format": ""
        },
        {
            "name": "query",
            "baseName": "query",
            "type": "any",
            "format": ""
        },
        {
            "name": "kind",
            "baseName": "kind",
            "type": "string",
            "format": ""
        },
        {
            "name": "createdAt",
            "baseName": "created_at",
            "type": "string",
            "format": ""
        },
        {
            "name": "groupHash",
            "baseName": "group_hash",
            "type": "string",
            "format": ""
        },
        {
            "name": "level",
            "baseName": "level",
            "type": "RecordLevel",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return Record.attributeTypeMap;
    }

    public constructor() {
    }
}

