/**
 * Moonlogs
 * Moonlogs API
 *
 * OpenAPI spec version: 0.5.10
 * Contact: shalpack@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { SchemaField } from '../models/SchemaField';
import { SchemaKind } from '../models/SchemaKind';
import { HttpFile } from '../http/http';

export class Schema {
    'id': number;
    'title': string;
    'description'?: string;
    'name': string;
    'fields': Array<SchemaField>;
    'kinds': Array<SchemaKind>;
    'tagId'?: number;
    'retentionDays'?: number;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "id",
            "baseName": "id",
            "type": "number",
            "format": ""
        },
        {
            "name": "title",
            "baseName": "title",
            "type": "string",
            "format": ""
        },
        {
            "name": "description",
            "baseName": "description",
            "type": "string",
            "format": ""
        },
        {
            "name": "name",
            "baseName": "name",
            "type": "string",
            "format": ""
        },
        {
            "name": "fields",
            "baseName": "fields",
            "type": "Array<SchemaField>",
            "format": ""
        },
        {
            "name": "kinds",
            "baseName": "kinds",
            "type": "Array<SchemaKind>",
            "format": ""
        },
        {
            "name": "tagId",
            "baseName": "tag_id",
            "type": "number",
            "format": ""
        },
        {
            "name": "retentionDays",
            "baseName": "retention_days",
            "type": "number",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return Schema.attributeTypeMap;
    }

    public constructor() {
    }
}

