/**
 * Moonlogs
 * Moonlogs API
 *
 * OpenAPI spec version: 0.5.10
 * Contact: shalpack@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { UserRole } from '../models/UserRole';
import { HttpFile } from '../http/http';

export class User {
    'id': number;
    'name': string;
    'email': string;
    'password': string;
    'passwordDigest'?: string;
    'role': UserRole;
    'tags': Array<number>;
    'token'?: string;
    'isRevoked': boolean;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "id",
            "baseName": "id",
            "type": "number",
            "format": ""
        },
        {
            "name": "name",
            "baseName": "name",
            "type": "string",
            "format": ""
        },
        {
            "name": "email",
            "baseName": "email",
            "type": "string",
            "format": ""
        },
        {
            "name": "password",
            "baseName": "password",
            "type": "string",
            "format": ""
        },
        {
            "name": "passwordDigest",
            "baseName": "password_digest",
            "type": "string",
            "format": ""
        },
        {
            "name": "role",
            "baseName": "role",
            "type": "UserRole",
            "format": ""
        },
        {
            "name": "tags",
            "baseName": "tags",
            "type": "Array<number>",
            "format": ""
        },
        {
            "name": "token",
            "baseName": "token",
            "type": "string",
            "format": ""
        },
        {
            "name": "isRevoked",
            "baseName": "is_revoked",
            "type": "boolean",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return User.attributeTypeMap;
    }

    public constructor() {
    }
}

