/* tslint:disable */
/* eslint-disable */
/**
 * Moonlogs
 * Moonlogs API
 *
 * The version of the OpenAPI document: 0.5.9
 * Contact: shalpack@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ApiToken
 */
export interface ApiToken {
    /**
     * 
     * @type {number}
     * @memberof ApiToken
     */
    id: number;
    /**
     * 
     * @type {string}
     * @memberof ApiToken
     */
    token: string;
    /**
     * 
     * @type {string}
     * @memberof ApiToken
     */
    name: string;
    /**
     * 
     * @type {boolean}
     * @memberof ApiToken
     */
    isRevoked: boolean;
}

export function ApiTokenFromJSON(json: any): ApiToken {
    return ApiTokenFromJSONTyped(json, false);
}

export function ApiTokenFromJSONTyped(json: any, ignoreDiscriminator: boolean): ApiToken {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': json['id'],
        'token': json['token'],
        'name': json['name'],
        'isRevoked': json['is_revoked'],
    };
}

export function ApiTokenToJSON(value?: ApiToken | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'id': value.id,
        'token': value.token,
        'name': value.name,
        'is_revoked': value.isRevoked,
    };
}

