/* tslint:disable */
/* eslint-disable */
/**
 * Moonlogs
 * Moonlogs API
 *
 * The version of the OpenAPI document: 0.5.10
 * Contact: shalpack@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    Meta,
    MetaFromJSON,
    MetaFromJSONTyped,
    MetaToJSON,
} from './Meta';
import {
    Schema,
    SchemaFromJSON,
    SchemaFromJSONTyped,
    SchemaToJSON,
} from './Schema';

/**
 * 
 * @export
 * @interface InlineResponse200
 */
export interface InlineResponse200 {
    /**
     * 
     * @type {boolean}
     * @memberof InlineResponse200
     */
    success: boolean;
    /**
     * 
     * @type {number}
     * @memberof InlineResponse200
     */
    code: number;
    /**
     * 
     * @type {string}
     * @memberof InlineResponse200
     */
    error: string;
    /**
     * 
     * @type {Array<Schema>}
     * @memberof InlineResponse200
     */
    data: Array<Schema>;
    /**
     * 
     * @type {Meta}
     * @memberof InlineResponse200
     */
    meta: Meta;
}

export function InlineResponse200FromJSON(json: any): InlineResponse200 {
    return InlineResponse200FromJSONTyped(json, false);
}

export function InlineResponse200FromJSONTyped(json: any, ignoreDiscriminator: boolean): InlineResponse200 {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'success': json['success'],
        'code': json['code'],
        'error': json['error'],
        'data': ((json['data'] as Array<any>).map(SchemaFromJSON)),
        'meta': MetaFromJSON(json['meta']),
    };
}

export function InlineResponse200ToJSON(value?: InlineResponse200 | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'success': value.success,
        'code': value.code,
        'error': value.error,
        'data': ((value.data as Array<any>).map(SchemaToJSON)),
        'meta': MetaToJSON(value.meta),
    };
}

