/* tslint:disable */
/* eslint-disable */
/**
 * Moonlogs
 * Moonlogs API
 *
 * The version of the OpenAPI document: 0.5.10
 * Contact: shalpack@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    ApiToken,
    ApiTokenFromJSON,
    ApiTokenFromJSONTyped,
    ApiTokenToJSON,
} from './ApiToken';
import {
    Meta,
    MetaFromJSON,
    MetaFromJSONTyped,
    MetaToJSON,
} from './Meta';

/**
 * 
 * @export
 * @interface InlineResponse2009
 */
export interface InlineResponse2009 {
    /**
     * 
     * @type {boolean}
     * @memberof InlineResponse2009
     */
    success: boolean;
    /**
     * 
     * @type {number}
     * @memberof InlineResponse2009
     */
    code: number;
    /**
     * 
     * @type {string}
     * @memberof InlineResponse2009
     */
    error: string;
    /**
     * 
     * @type {Array<ApiToken>}
     * @memberof InlineResponse2009
     */
    data: Array<ApiToken>;
    /**
     * 
     * @type {Meta}
     * @memberof InlineResponse2009
     */
    meta: Meta;
}

export function InlineResponse2009FromJSON(json: any): InlineResponse2009 {
    return InlineResponse2009FromJSONTyped(json, false);
}

export function InlineResponse2009FromJSONTyped(json: any, ignoreDiscriminator: boolean): InlineResponse2009 {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'success': json['success'],
        'code': json['code'],
        'error': json['error'],
        'data': ((json['data'] as Array<any>).map(ApiTokenFromJSON)),
        'meta': MetaFromJSON(json['meta']),
    };
}

export function InlineResponse2009ToJSON(value?: InlineResponse2009 | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'success': value.success,
        'code': value.code,
        'error': value.error,
        'data': ((value.data as Array<any>).map(ApiTokenToJSON)),
        'meta': MetaToJSON(value.meta),
    };
}

