/* tslint:disable */
/* eslint-disable */
/**
 * Moonlogs
 * Moonlogs API
 *
 * The version of the OpenAPI document: 0.5.10
 * Contact: shalpack@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface SchemaField
 */
export interface SchemaField {
    /**
     * 
     * @type {string}
     * @memberof SchemaField
     */
    title: string;
    /**
     * 
     * @type {string}
     * @memberof SchemaField
     */
    name: string;
}

export function SchemaFieldFromJSON(json: any): SchemaField {
    return SchemaFieldFromJSONTyped(json, false);
}

export function SchemaFieldFromJSONTyped(json: any, ignoreDiscriminator: boolean): SchemaField {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'title': json['title'],
        'name': json['name'],
    };
}

export function SchemaFieldToJSON(value?: SchemaField | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'title': value.title,
        'name': value.name,
    };
}

