/* tslint:disable */
/* eslint-disable */
/**
 * Moonlogs
 * Moonlogs API
 *
 * The version of the OpenAPI document: 0.5.10
 * Contact: shalpack@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface SchemaKind
 */
export interface SchemaKind {
    /**
     * 
     * @type {string}
     * @memberof SchemaKind
     */
    title: string;
    /**
     * 
     * @type {string}
     * @memberof SchemaKind
     */
    name: string;
}

export function SchemaKindFromJSON(json: any): SchemaKind {
    return SchemaKindFromJSONTyped(json, false);
}

export function SchemaKindFromJSONTyped(json: any, ignoreDiscriminator: boolean): SchemaKind {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'title': json['title'],
        'name': json['name'],
    };
}

export function SchemaKindToJSON(value?: SchemaKind | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'title': value.title,
        'name': value.name,
    };
}

