/**
 * Moonlogs
 * Moonlogs API
 *
 * The version of the OpenAPI document: 0.5.8
 * Contact: shalpack@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

export enum Level {
    Trace = <any> 'Trace',
    Debug = <any> 'Debug',
    Info = <any> 'Info',
    Warn = <any> 'Warn',
    Error = <any> 'Error',
    Fatal = <any> 'Fatal'
}
