/**
 * Moonlogs
 * Moonlogs API
 *
 * The version of the OpenAPI document: 0.5.8
 * Contact: shalpack@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { Level } from './level';

export class RecordLevel {

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
    ];

    static getAttributeTypeMap() {
        return RecordLevel.attributeTypeMap;
    }
}

