/**
 * Moonlogs
 * Moonlogs API
 *
 * The version of the OpenAPI document: 0.5.9
 * Contact: shalpack@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { RecordLevel } from './recordLevel';

export class Record {
    'id': number;
    'text': string;
    'schemaName': string;
    'schemaId'?: number;
    'query': object;
    'kind': string;
    'createdAt'?: string;
    'groupHash'?: string;
    'level'?: RecordLevel;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "id",
            "baseName": "id",
            "type": "number"
        },
        {
            "name": "text",
            "baseName": "text",
            "type": "string"
        },
        {
            "name": "schemaName",
            "baseName": "schema_name",
            "type": "string"
        },
        {
            "name": "schemaId",
            "baseName": "schema_id",
            "type": "number"
        },
        {
            "name": "query",
            "baseName": "query",
            "type": "object"
        },
        {
            "name": "kind",
            "baseName": "kind",
            "type": "string"
        },
        {
            "name": "createdAt",
            "baseName": "created_at",
            "type": "string"
        },
        {
            "name": "groupHash",
            "baseName": "group_hash",
            "type": "string"
        },
        {
            "name": "level",
            "baseName": "level",
            "type": "RecordLevel"
        }    ];

    static getAttributeTypeMap() {
        return Record.attributeTypeMap;
    }
}

