/**
 * Moonlogs
 * Moonlogs API
 *
 * The version of the OpenAPI document: 0.5.9
 * Contact: shalpack@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { SchemaField } from './schemaField';
import { SchemaKind } from './schemaKind';

export class Schema {
    'id': number;
    'title': string;
    'description'?: string;
    'name': string;
    'fields': Array<SchemaField>;
    'kinds': Array<SchemaKind>;
    'tagId'?: number;
    'retentionDays'?: number;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "id",
            "baseName": "id",
            "type": "number"
        },
        {
            "name": "title",
            "baseName": "title",
            "type": "string"
        },
        {
            "name": "description",
            "baseName": "description",
            "type": "string"
        },
        {
            "name": "name",
            "baseName": "name",
            "type": "string"
        },
        {
            "name": "fields",
            "baseName": "fields",
            "type": "Array<SchemaField>"
        },
        {
            "name": "kinds",
            "baseName": "kinds",
            "type": "Array<SchemaKind>"
        },
        {
            "name": "tagId",
            "baseName": "tag_id",
            "type": "number"
        },
        {
            "name": "retentionDays",
            "baseName": "retention_days",
            "type": "number"
        }    ];

    static getAttributeTypeMap() {
        return Schema.attributeTypeMap;
    }
}

