/**
 * Moonlogs
 * Moonlogs API
 *
 * The version of the OpenAPI document: 0.5.9
 * Contact: shalpack@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { UserRole } from './userRole';

export class User {
    'id': number;
    'name': string;
    'email': string;
    'password': string;
    'passwordDigest'?: string;
    'role': UserRole;
    'tags': Array<number>;
    'token'?: string;
    'isRevoked': boolean;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "id",
            "baseName": "id",
            "type": "number"
        },
        {
            "name": "name",
            "baseName": "name",
            "type": "string"
        },
        {
            "name": "email",
            "baseName": "email",
            "type": "string"
        },
        {
            "name": "password",
            "baseName": "password",
            "type": "string"
        },
        {
            "name": "passwordDigest",
            "baseName": "password_digest",
            "type": "string"
        },
        {
            "name": "role",
            "baseName": "role",
            "type": "UserRole"
        },
        {
            "name": "tags",
            "baseName": "tags",
            "type": "Array<number>"
        },
        {
            "name": "token",
            "baseName": "token",
            "type": "string"
        },
        {
            "name": "isRevoked",
            "baseName": "is_revoked",
            "type": "boolean"
        }    ];

    static getAttributeTypeMap() {
        return User.attributeTypeMap;
    }
}

