name: Generate and Publish Typescript Client

on:
  repository_dispatch:
    types: [generate-publish-client]

permissions:
  contents: write


jobs:
  generate-and-publish-client:
    runs-on: ubuntu-latest
    env:
      NPM_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Download Swagger YAML
        run: |
          curl -sSLo swagger.yaml https://raw.githubusercontent.com/pijng/moonlogs/master/internal/api/swagger.yaml

      - name: Download Swagger Codegen
        run: |
         wget https://repo1.maven.org/maven2/io/swagger/codegen/v3/swagger-codegen-cli/3.0.52/swagger-codegen-cli-3.0.52.jar -O swagger-codegen-cli.jar

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
          registry-url: 'https://registry.npmjs.org'

      - name: Generate Typescript Client
        run: |
          npm install @openapitools/openapi-generator-cli -g
          openapi-generator-cli generate -g typescript-node -i swagger.yaml -o moonlogs-ts --additional-properties=supportES6=true,npmName=moonlogs-ts,npmVersion==${{ github.event.client_payload.tag_version }} --skip-validate-spec
          rm swagger.yaml

      - name: Commit & Push changes
        uses: actions-js/push@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          force: true
          branch: master

      - name: Build and publish package
        run: |
          cd moonlogs-ts
          npm install
          npm run build
          npm ci
          npm publish
